// AUTO-GENERATED by `bun run codegen`. Do not edit by hand.
import { defineConfig } from 'tsdown'

export default defineConfig({
	entry: {
		'core/index': 'src/core/index.ts',
		'http/index': 'src/http/index.ts',
		'mastra/index': 'src/adapters/mastra/index.ts',
		'ai-sdk/index': 'src/adapters/ai-sdk/index.ts',
		'tanstack/index': 'src/adapters/tanstack/index.ts',
		'cloudflare/index': 'src/adapters/cloudflare/index.ts',
		'mcp/index': 'src/adapters/mcp/index.ts',
		'modules/document-extract/index': 'src/modules/document-extract/index.ts',
		'modules/document-render/index': 'src/modules/document-render/index.ts',
		'modules/email/index': 'src/modules/email/index.ts',
		'modules/file-convert/index': 'src/modules/file-convert/index.ts',
		'modules/files/index': 'src/modules/files/index.ts',
		'modules/media-type/index': 'src/modules/media-type/index.ts',
		'modules/mime/index': 'src/modules/mime/index.ts',
		'modules/storage/index': 'src/modules/storage/index.ts',
		'modules/web-fetch/index': 'src/modules/web-fetch/index.ts'
	},
	format: ['esm'],
	// package.json is "type": "module" — emit .js / .d.ts (not .mjs / .d.mts)
	fixedExtension: false,
	dts: true,
	sourcemap: true,
	deps: {
		neverBundle: [
			'@mastra/core',
			'@modelcontextprotocol/sdk',
			'@tanstack/ai',
			'ai',
			'aws4fetch',
			'es-toolkit',
			'mime',
			'mimetext',
			'ofetch',
			'postal-mime',
			'zod'
		]
	}
})
