/**
 * Object-store vertical kit for vendor packs only.
 * Not published — directory name `_storage` is skipped by surface codegen.
 */

export {
	abortMultipartUploadInputSchema,
	abortMultipartUploadOutputSchema,
	completeMultipartUploadInputSchema,
	completeMultipartUploadOutputSchema,
	copyObjectInputSchema,
	copyObjectOutputSchema,
	createMultipartUploadInputSchema,
	createMultipartUploadOutputSchema,
	DEFAULT_SIGNED_URL_SECONDS,
	deleteObjectInputSchema,
	deleteObjectOutputSchema,
	deleteObjectsInputSchema,
	deleteObjectsOutputSchema,
	getObjectInputSchema,
	getObjectOutputSchema,
	getObjectsInputSchema,
	getObjectsOutputSchema,
	headObjectInputSchema,
	headObjectOutputSchema,
	listObjectsInputSchema,
	listObjectsOutputSchema,
	listedObjectSchema,
	MAX_BATCH_ITEMS,
	MAX_MULTIPART_PART_BYTES,
	MAX_OBJECT_BYTES,
	MAX_SIGNED_URL_SECONDS,
	multipartUploadedPartSchema,
	putObjectInputSchema,
	putObjectOutputSchema,
	putObjectsInputSchema,
	putObjectsOutputSchema,
	signedUrlInputSchema,
	signedUrlOutputSchema,
	uploadPartInputSchema,
	uploadPartOutputSchema
} from './schemas'
export type {
	AbortMultipartUploadInput,
	AbortMultipartUploadOutput,
	CompleteMultipartUploadInput,
	CompleteMultipartUploadOutput,
	CopyObjectInput,
	CopyObjectOutput,
	CreateMultipartUploadInput,
	CreateMultipartUploadOutput,
	DeleteObjectInput,
	DeleteObjectOutput,
	GetObjectInput,
	GetObjectOutput,
	HeadObjectInput,
	HeadObjectOutput,
	ListObjectsInput,
	ListObjectsOutput,
	PutObjectInput,
	PutObjectOutput,
	SignedUrlInput,
	SignedUrlOutput,
	UploadPartInput,
	UploadPartOutput
} from './schemas'
